[package]
name = "snippet_matcher"
version.workspace = true
edition.workspace = true

[dependencies]
aho-corasick = "1.1.4"
parking_lot.workspace = true
serde.workspace = true

shared_utils = { path = "../shared_utils" }

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[lints]
workspace = true
