[package]
name = "app_storage"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rkyv.workspace = true
bytecheck = "0.8"
storage_utils = { path = "../storage_utils" }

[dev-dependencies]
tempfile = "3.0"

[lints]
workspace = true
