[package]
name = "calculator"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
evalexpr = "13.0.0"
chrono = "0.4"
chrono-tz = "0.10.4"
rustc-hash.workspace = true

[lints]
workspace = true
